apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        envFrom:
        - configMapRef:
            name: example-config
        ports:
        - containerPort: 5432
          name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: example-api-svc
  labels:
    app: example-api
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30050
  selector:
    app: example-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-api
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: example-api
    spec:
      containers:
      - name: example-api
        image: qbob/api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: example-site-svc
  labels:
    app: example-site
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30051
  selector:
    app: example-site
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-site
spec:
  replicas: 1
  template: 
    metadata: 
      labels:
        app: example-site
    spec:
      containers:
      - name: example-site
        image: qbob/frontend
        envFrom:
        ports:
        - containerPort: 8080
---
